<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find ouster_description)/urdf/OS1-128.urdf.xacro" />
  <xacro:macro name="os1128_mount" params="prefix parent_link topic height:=0.12 *origin">
    <!--
      The VLP16 is mounted to a pair of extrusion rods on top of the main sensor arch
    -->
    <link name="${prefix}os1128_mount_base_link" />
    <link name="${prefix}os1128_mount_plate">
      <visual>
        <geometry>
          <box size="0.04 0.141 0.0063" />
        </geometry>
        <material name="black">
          <color rgba="1 1 1 1" />
        </material>
        <origin xyz="0 0 0.00315" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.02 ${height}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
    </link>
    <link name="${prefix}os1128_mount_left_support">
      <visual>
        <geometry>
          <box size="0.04 0.02 ${height}" />
        </geometry>
        <material name="black">
          <color rgba="1 1 1 1" />
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.02 ${height}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
    </link>
    <link name="${prefix}os1128_mount_right_support">
      <visual>
        <geometry>
          <box size="0.04 0.02 ${height}" />
        </geometry>
        <material name="black">
          <color rgba="1 1 1 1" />
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.02 ${height}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
    </link>

    <joint name="${prefix}os1128_mount_base_link_joint" type="fixed">
      <parent link="${parent_link}" />
      <child link="${prefix}os1128_mount_base_link" />
      <xacro:insert_block name="origin" />
    </joint>
    <joint name="${prefix}os1128_mount_left_support_joint" type="fixed">
      <parent link="${prefix}os1128_mount_base_link" />
      <child link="${prefix}os1128_mount_left_support" />
      <origin xyz="0 0.06 ${height/2}" rpy="0 0 0"/>
    </joint>
    <joint name="${prefix}os1128_mount_right_support_joint" type="fixed">
      <parent link="${prefix}os1128_mount_base_link" />
      <child link="${prefix}os1128_mount_right_support" />
      <origin xyz="0 -0.06 ${height/2}" rpy="0 0 0"/>
    </joint>
    <joint name="${prefix}os1128_mount_plate_joint" type="fixed">
      <parent link="${prefix}os1128_mount_base_link" />
      <child link="${prefix}os1128_mount_plate" />
      <origin xyz="0 0 ${height}" rpy="0 0 0"/>
    </joint>

    <xacro:VLP-16 parent="${prefix}os1128_mount_plate" topic="${topic}" name="${prefix}ouster">
      <origin xyz="0 0 0.0063" rpy="0 0 0" />
    </xacro:VLP-16>
  </xacro:macro>
</robot>
